### ISSUE TITLE
Different system compile error

### ISSUE THREAD

**Issue by Yo1ick** [stressapptest/stressapptest#98]
Hi 
     18 days in a line Git stats 69 commits  Exist in version.  [https://github.com/stressapptest/stressapptest](url) . #96   #97
`
Making all in src
make[1]: Entering directory '/tmp/stressapptest-master/src'
make  all-am
make[2]: Entering directory '/tmp/stressapptest-master/src'
g++ -DHAVE_CONFIG_H -I.     -DCHECKOPTS -Wreturn-type -Wunused -Wuninitialized -Wall -O3 -funroll-all-loops  -funroll-loops -DNDEBUG -MT main.o -MD -MP -MF .deps/main.Tpo -c -o main.o main.cc
In file included from finelock_queue.h:29,
                 from sat.h:28,
                 from main.cc:18:
os.h: In static member function ‘static uint64 OsLayer::GetTimestamp()’:
os.h:284:11: error: ‘__rdtsc’ was not declared in this scope
     tsc = __rdtsc();
           ^~~~~~~
os.h:284:11: note: suggested alternative: ‘__dt ’
     tsc = __rdtsc();
           ^~~~~~~
           __dt
make[2]: *** [Makefile:326: main.o] Error 1
make[2]: Leaving directory '/tmp/stressapptest-master/src'
make[1]: *** [Makefile:192: all] Error 2
make[1]: Leaving directory '/tmp/stressapptest-master/src'
make: *** [Makefile:312: all-recursive] Error 1
`
This error occurs when you are compiling on centos8.3 debian10.9, but not when you are compiling on ubuntu20.04

**Comment by sebhz** [comment]
Hi,

I had a quick look at this using a debian 10 docker container, and could repro the issue. It looks like debian 10 uses gcc 8.3, which needs x86intrin.h include to find __rdtsc() intrinsic. Below patch fixes the problem. No time to check on CentOS8.3, though. I do not claim this is the right solution - [stackoverflow](https://stackoverflow.com/questions/13772567/how-to-get-the-cpu-cycle-count-in-x86-64-from-c/51907627#51907627) seems to think that x86intrin.h is the correct include, but it is obviously not needed for gcc 9.4 used in Ubuntu.
```
diff --git a/src/os.h b/src/os.h
index 06987f9..f170991 100644
--- a/src/os.h
+++ b/src/os.h
@@ -34,6 +34,7 @@

 #if defined(STRESSAPPTEST_CPU_X86_64) || defined(STRESSAPPTEST_CPU_I686)
 #include <immintrin.h>
+#include <x86intrin.h>
 #if defined(_MSC_VER)
 #include <intrin.h>
 #endif
```

**Comment by Qwinn1** [comment]
Oddly I get this exact same error attempting to compile on Ubuntu 20.04 on a USB stick.

**Comment by daytimothy** [comment]
The proposed fix worked for me on RHEL 8.6/8.7.

**Comment by scpawar9** [comment]
adding helped to compile
include <x86intrin.h>

**Comment by sheepman0** [comment]
adding include <x86intrin.h> helped me too on Debian 10.13, without it the packaged version stalled exactly as described here.

**Comment by bssrikanth** [comment]
The proposed fix worked for me on ubuntu 20.04.

**Comment by bssrikanth** [comment]
Do you have any timelines on getting this fixed via PR?

**Comment by dzhengfy** [comment]
@sebhz, do you plan to fix it? This problem is blocking our test on RHEL8.x. Thanks

**Comment by sebhz** [comment]
PR opened: https://github.com/stressapptest/stressapptest/pull/105

**Comment by sebhz** [comment]
https://github.com/stressapptest/stressapptest/pull/105 was merged. This issue can probably be closed.
